import sys
import os

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required.")
    sys.exit(1)

TILE_COLORS = {
    (197, 0, 0): 0,         
    (197, 194, 0): 2,       
    (0, 92, 197): 3,        
    (56, 197, 0): 4,        
    (0, 197, 173): 100,     
}
DEFAULT_TILE = 0           
COLOR_TOLERANCE = 10       

def color_matches(pixel, target, tolerance):
    return all(abs(pixel[i] - target[i]) <= tolerance for i in range(3))

def pixel_to_tile(r, g, b):
    for color, tile_id in TILE_COLORS.items():
        if color_matches((r, g, b), color, COLOR_TOLERANCE):
            return tile_id
    return DEFAULT_TILE

def convert(input_path, output_path, config):
    crop = config.get("crop", None)
    
    if not os.path.isfile(input_path):
        print(f"Error: File not found: {input_path}")
        sys.exit(1)

    img = Image.open(input_path).convert("RGB")

    if crop and len(crop) == 4:
        x, y, w, h = crop
        img = img.crop((x, y, x + w, y + h))
        print(f"Cropped to region: x={x}, y={y}, w={w}, h={h}")

    img = img.transpose(Image.ROTATE_180)

    width, height = img.size
    print(f"Map size: {width}x{height} tiles")

    rows = []
    for row_y in range(height):
        row = []
        for col_x in range(width):
            r, g, b = img.getpixel((col_x, row_y))
            row.append(pixel_to_tile(r, g, b))
        rows.append(row)

    guard = os.path.basename(output_path).upper().replace(".", "_").replace("-", "_")

    with open(output_path, "w") as f:
        f.write(f"// Auto-generated by texture2collision.py\n#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        f.write(f"#define MAP_WIDTH  {width}\n#define MAP_HEIGHT {height}\n\n")
        f.write(f"static const uint8_t collision_map[MAP_HEIGHT][MAP_WIDTH] = {{\n")
        for row in rows: f.write("    {" + ", ".join(str(t) for t in row) + "},\n")
        f.write("};\n\n#endif\n")

    print(f"Written to: {output_path}")

if __name__ == "__main__":
    args = sys.argv[1:]
    input_path  = args[0]
    output_path = args[1]
    crop = None
    
    if len(args) == 6:
        crop = (int(args[2]), int(args[3]), int(args[4]), int(args[5]))
        
    convert(input_path, output_path, {"crop": crop})