#pragma once
// Auto-generated by obj2environment.py
// Source: iwatodai_dorm.obj
// Scale: 1.272727  Centred: True  max_tex_size: None
// DO NOT EDIT - regenerate from source.

#include <nds.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

// World bounds
#define IWATODAI_DORM_WORLD_OFFSET_X 1.750000f
#define IWATODAI_DORM_WORLD_OFFSET_Z 1.312500f
#define IWATODAI_DORM_WORLD_WIDTH    3.500000f
#define IWATODAI_DORM_WORLD_DEPTH    2.625000f

enum iwatodai_dorm_TexSlot {
    IWATODAI_DORM_TEX_TEXTURE = 0,
    IWATODAI_DORM_TEX_COUNT = 1
};

struct iwatodai_dorm_BillboardData {
    v16 x, y, z;
    v16 halfWidth, halfHeight;
    int texSlot;
    short u0, v0, u1, v1;
};

class iwatodai_dorm_Environment {
public:
    u32* displayLists[1];
    u32  dlSizes[1];
    int  textureIDs[1];

    static const int BILLBOARD_COUNT = 4;
    const iwatodai_dorm_BillboardData BILLBOARDS[4] = {
        { 3258, 651, 814, 407, 244, 0, 96, 1088, 128, 1136 },
        { 2280, 651, 814, 407, 244, 0, 416, 1088, 448, 1136 },
        { 1303, 977, 814, 244, 570, 0, 304, 1039, 368, 1072 },
        { 4235, 977, 814, 244, 570, 0, 384, 1039, 448, 1072 },
    };

    iwatodai_dorm_Environment() {
        for (int i = 0; i < 1; i++) {
            displayLists[i] = NULL; dlSizes[i] = 0; textureIDs[i] = 0;
        }
    }

    bool load(const char* filepath, const unsigned int* bitmaps[1]) {
        FILE* file = fopen(filepath, "rb");
        if (!file) return false;

        char magic[4];
        fread(magic, 1, 4, file);
        if (magic[0]!='E'||magic[1]!='N'||magic[2]!='V'||magic[3]!='1') {
            fclose(file); return false;
        }

        u32 groupCount;
        fread(&groupCount, sizeof(u32), 1, file);
        if (groupCount != 1) { fclose(file); return false; }

        for (u32 i = 0; i < groupCount; i++) {
            fread(&dlSizes[i], sizeof(u32), 1, file);
            displayLists[i] = (u32*)malloc((dlSizes[i] + 1) * sizeof(u32));
            displayLists[i][0] = dlSizes[i];
            if (dlSizes[i] > 0)
                fread(&displayLists[i][1], sizeof(u32), dlSizes[i], file);
        }
        fclose(file);

        if (bitmaps[0]) {
            glGenTextures(1, &textureIDs[0]);
            glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEXTURE_SIZE_256, TEXTURE_SIZE_256, 0,
                TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T,
                bitmaps[0]);
        }
        return true;
    }

    int getPolyCount() const {
        int total = 0;
        for (int i = 0; i < 1; i++) {
            if (dlSizes[i] > 0) {
                const u32* dl = &displayLists[i][1];
                for (u32 j = 0; j < dlSizes[i]; j++) {
                    u32 w = dl[j];
                    for (int b = 0; b < 4; b++) {
                        if (((w >> (b * 8)) & 0xFF) == 0x40) total++;
                    }
                }
            }
        }
        return total;
    }

    void draw() {
        glBindTexture(GL_TEXTURE_2D, textureIDs[0]);
        if (displayLists[0]) glCallList(displayLists[0]);
        while (GFX_BUSY);
    }

    void drawBillboards(bool faceCamera, float camX, float camY, float camZ) {
        if (BILLBOARD_COUNT == 0) return;
        int  currentSlot = -1;
        bool inQuads     = false;

        for (int i = 0; i < BILLBOARD_COUNT; i++) {
            const iwatodai_dorm_BillboardData& bb = BILLBOARDS[i];
            if (bb.texSlot != currentSlot) {
                if (inQuads) { glEnd(); inQuads = false; }
                while (GFX_BUSY);
                glBindTexture(GL_TEXTURE_2D, textureIDs[bb.texSlot]);
                currentSlot = bb.texSlot;
            }
            if (!inQuads) { glBegin(GL_QUADS); inQuads = true; }

            v16 rX = (v16)(4096), rY = 0, rZ = 0;
            v16 uX = 0, uY = (v16)(4096), uZ = 0;

            if (faceCamera) {
                float bx = (float)bb.x / 4096.0f;
                float bz = (float)bb.z / 4096.0f;
                float dx = camX - bx, dz = camZ - bz;
                float dist = sqrtf(dx*dx + dz*dz);
                if (dist > 0.001f) { dx /= dist; dz /= dist; }
                rX = (v16)(dz * 4096.0f);
                rZ = (v16)(-dx * 4096.0f);
            }

            v16 rx = mulf32(rX, bb.halfWidth),  ry = mulf32(rY, bb.halfWidth),  rz = mulf32(rZ, bb.halfWidth);
            v16 ux = mulf32(uX, bb.halfHeight), uy = mulf32(uY, bb.halfHeight), uz = mulf32(uZ, bb.halfHeight);

            glTexCoord2t16(bb.u0, bb.v1); glVertex3v16(bb.x-rx-ux, bb.y-ry-uy, bb.z-rz-uz);
            glTexCoord2t16(bb.u1, bb.v1); glVertex3v16(bb.x+rx-ux, bb.y+ry-uy, bb.z+rz-uz);
            glTexCoord2t16(bb.u1, bb.v0); glVertex3v16(bb.x+rx+ux, bb.y+ry+uy, bb.z+rz+uz);
            glTexCoord2t16(bb.u0, bb.v0); glVertex3v16(bb.x-rx+ux, bb.y-ry+uy, bb.z-rz+uz);
        }
        if (inQuads) glEnd();
    }

    void cleanup() {
        for (u32 i = 0; i < 1; i++) {
            if (displayLists[i]) { free(displayLists[i]); displayLists[i] = NULL; }
        }
        glDeleteTextures(1, textureIDs);
    }
};
